version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predictive_sales_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run src/ui/streamlit_app/app.py --server.port 8501 --server.headless true

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_tracking
    environment:
      - MLFLOW_BACKEND_STORE_URI=/mlruns
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlruns
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "5000:5000"
